[package]
name = "server"
version = "0.0.0"
edition = "2024"
publish = false
rust-version = "1.85"

[dependencies]
rama = { version = "0.2.0", features = ["http-full"] }
serde = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
